name: bandit
on: [push, pull_request]
jobs:
  # Job name
  run_bandit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 # IMPORTANT
        # Every job must be separated by a hyphen ('-').
      - name: Setting up Python
        uses: actions/setup-python@main
        with:
          python-version: '3.11.1'
          cache: 'pip'
      
      - name: Installing bandit
        run: pip install "bandit[toml]"

      - name: bandit .
        run: bandit . -c ./config/pyproject.toml
