name: BLACKED
on: [push, pull_request]
jobs:
  # Job name
  run_black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 # IMPORTANT
        # Every job must be separated by a hyphen ('-').
      - name: Setting up Python
        uses: actions/setup-python@main
        with:
          python-version: '3.11.1'
          cache: 'pip'
      
      - name: Installing black
        run: pip install black

      - name: black .
        run: black . --config ./config/pyproject.toml
