name: flake8
on: [push, pull_request]
jobs:
  # Job name
  run_flake8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 # IMPORTANT
        # Every job must be separated by a hyphen ('-').
      - name: Setting up Python
        uses: actions/setup-python@main
        with:
          python-version: '3.11.1'
          cache: 'pip'
      
      - name: Installing flake8
        run: pip install flake8

      - name: flake8 .
        run: flake8 . --config ./config/.flake8
