name: mypy
on: [push, pull_request]
jobs:
  # Job name
  run_mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 # IMPORTANT
        # Every job must be separated by a hyphen ('-').
      - name: Setting up Python
        uses: actions/setup-python@main
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Installing dependencies
        run: pip install sqlalchemy-stubs

      - name: Installing mypy
        run: pip install mypy

      - name: Run mypy
        run: mypy . --config-file ./config/pyproject.toml
